<a href="https://colab.research.google.com/github/SOUVI11/Numpy-colab/blob/main/AI_JUPITER_TASK_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
###importing
import numpy as np

In [ ]:
###creating array
lst=[1,9,8,3]
print(lst)

[1, 9, 8, 3]


In [ ]:
###printing array
numpyarray=np.array(lst)
numpyarray

array([1, 9, 8, 3])

In [ ]:
###declaring and printing array
a=np.array([1,9,8,3])
print(a)

[1 9 8 3]


In [ ]:
###addition on an array
x=numpyarray+10
print(x)

[11 19 18 13]


In [ ]:
###shape and type of an array
a=np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int32


In [ ]:
###type of an float array
b=np.array([1.1,0.2,3.2])
print(b.dtype)

float64


In [ ]:
###2 dimension array
c=np.array([(1,2,3),
              (4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
###3 dimension
d=np.array([
    [[1,2,3],
         [4,5,6]],
    [[7,8,9],
        [10,11,12]]
])
print(d.shape)
print(d)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
###zero matrix
a=np.zeros((2,2), dtype=np.int16)
print(a)

[[0 0]
 [0 0]]


In [ ]:
### matrix with full one
a=np.ones((1,2,3), dtype=np.int16)
print(a.shape)
print(a)

(1, 2, 3)
[[[1 1 1]
  [1 1 1]]]


In [ ]:
###reshaping of an array
a=np.array([(1,2,3), (4,5,6)])
print(a)
a.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
###flattening an array
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
###appending horizontally in an array
a=np.array([1,2,3])
b=np.array([4,5,6])
print('Horizontal Append - ',np.hstack((a,b)))

Horizontal Append -  [1 2 3 4 5 6]


In [ ]:
###appending vertically in an array
print('Vertical Append - ',np.vstack((a,b)))

Vertical Append -  [[1 2 3]
 [4 5 6]]


In [ ]:
###random number
rarr=np.random.normal(5, 0.5, 10)
print(rarr)

[4.62770353 4.7211014  5.10900056 4.6330204  4.79869787 5.09694206
 5.09909865 4.60495671 4.86948054 5.14739744]


In [ ]:
### matrix with full one
m=np.matrix(np.ones((4,4)))
print(m)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
###converting an input to array
np.asarray(m)[2]=2
print(m)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [ ]:
###evenly spaced values within an interval
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
###evenly spaced values within an interval
np.arange(1, 10, 5)

array([1, 6])

In [ ]:
###evenly spaced values
np.linspace(1.0,10.0,num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
###evenly spaced values does not include stopvalue
np.linspace(1.0,5.0,num=5,endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [ ]:
###even spaced numbers on log scale
np.logspace(3.0,4.0,num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [ ]:
### item size
arr=np.array([1,2,3], dtype=np.complex128)
arr.itemsize

16

In [ ]:
arr=np.array([(1,2,3),(4,5,6)])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
### printing rows of an array
print('First row:', arr[0])
print('Second row:', arr[1])

First row: [1 2 3]
Second row: [4 5 6]


In [ ]:
### printing column of an array
print('Second column:',arr[:,1])

Second column: [2 5]


In [ ]:
### printing specified section of a row of an array
print(arr[1,:2])

[4 5]


In [ ]:
### printing specified section of a column of an array
print(arr[:2,1])

[2 5]


In [ ]:
normal_arr= np.random.normal(1,0.5,10)
print(normal_arr)

[1.09769828 0.41644457 0.45188391 1.3100068  0.36837237 1.03391684
 0.20740154 1.2304414  0.47840293 0.86182634]


In [ ]:
### printing minimum, maximum, mean, median, standard of an array
print('Minimum - ',np.min(arr))
print('Maximum - ',np.max(arr))
print('Mean - ',np.mean(arr))
print('Median - ',np.median(arr))
print('Standard - ',np.std(arr))

Minimum -  1
Maximum -  6
Mean -  3.5
Median -  3.5
Standard -  1.707825127659933


In [ ]:
### dot product of an array
a=np.array([1,2])
b=np.array([4,5])
np.dot(a,b)

14

In [ ]:
### multiplication of two matix
a=[[1,2],[3,4]] 
b=[[5,6],[7,8]] 
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

In [ ]:
###inverse of a matrix
A=np.array([[6, 3, 1],
              [3, -2, 5],
              [2, 6, 7]])
print(np.linalg.inv(A))

[[ 0.16        0.05454545 -0.06181818]
 [ 0.04       -0.14545455  0.09818182]
 [-0.08        0.10909091  0.07636364]]


In [ ]:
### det of a matrix
arr= np.array([[1, 2], [3,4]])
print("Matrix is:")
print(arr)
print("\nDet :",int(np.linalg.det(arr)))

Matrix is:
[[1 2]
 [3 4]]

Det : -2


In [ ]:
# rank of a matrix
marr=np.array([[1,1,1],[0,1,2],[1,5,3],[2,3,4]]) 
np.linalg.matrix_rank(marr)

3

In [ ]:
# eighenvalues and eighenvectors of a matrix
ex_matrix=np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(ex_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00  2.80575969e-16 -8.29646454e-16] [[-0.15115432 -0.72704996 -0.01128698 -0.250341  ]
 [-0.34923733 -0.28320876  0.42321091  0.69689908]
 [-0.54732033  0.16063243 -0.81256087 -0.64277516]
 [-0.74540333  0.60447363  0.40063694  0.19621708]]


In [ ]:
# diagonal element of a matrix
dmat=np.matrix('[5, 1; 14, 3]')
diag=dmat.diagonal()
print(diag)

[[5 3]]


In [ ]:
#transpose of a matrix
mat=np.matrix('[5, 1; 14, 3]')
trans=mat.transpose()
print(trans)

[[ 5 14]
 [ 1  3]]


In [ ]:
# trace of a matrix
mat=np.matrix('[5, 1; 14, 3]')
tracem=mat.trace()
print(tracem)

[[8]]


In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 11

array([12, 13, 14, 15])

In [ ]:
a - 4

array([-3, -2, -1,  0])

In [ ]:
a * 6

array([ 6, 12, 18, 24])

In [ ]:
a / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [ ]:
b=np.array([1,2,3,4])
a + b

array([2, 4, 6, 8])

In [ ]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [ ]:
# cos value
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# sin value
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])